import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { StarknetProvider } from '@/components/StarknetProvider';
import { bowlby_one, poppins, roboto } from './fonts';
import Alert from '@/components/Alert';
import { AlertProvider } from '@/hooks/useAlert';
import { themeScript } from './theme-script';
import { ArgentInvisibleProvider } from '@/provider/ArgentInvisibleProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${inter.className} ${poppins.variable}
         ${bowlby_one.variable} ${roboto.variable} bg-secondary `}
      >
        <StarknetProvider>
          <AlertProvider>
            <ArgentInvisibleProvider>{children}</ArgentInvisibleProvider>

            <Alert />
          </AlertProvider>
        </StarknetProvider>
      </body>
    </html>
  );
}
